### ISSUE TITLE
Link local Tzstat with local tzindex

### ISSUE THREAD

**Issue by grouville** [blockwatch-cc/tzstats#48]
Hello @echa,

Following the directives you explained to me on the tzindex repository, I have been trying for 2 days to connect my local tzindex with a local Tzstats. Unfortunately, I might be missing something, because it still doesn't connect.

Here are below the instructions you gave me (to avoid going back and forth on the tzindex repo) :
```
About your last question, you can run a local copy of https://github.com/blockwatch-cc/tzstats and link it to your local instance of tzindexer in a few different ways. Easiest by far is using the provided Docker images.

The way tzstats and web browsers work is that you need a local webserver to serve all files. You can setup a local nginx or use my embedded webserver serve. Key trick is that the TzStats JS file contains a template variable which gets replaced to point to the API endpoint.

1. Checkout the tzstats repo, create a new top-level file development.env with a single line TZSTATS_API_URL=http://localhost:8000, run npm install and then yarn start. You need NodeJS for this to work.
2. Copy all files from /var/www/ out of the tzstats Docker image, compile a local version of https://github.com/echa/serve and run serve with the following env variables: TZSTATS_API_URL (http://localhost:8000), SV_SERVER_PORT (smth other than the default port 8000 because tzindexer already uses it), SV_SERVER_ROOT (the directory you extracted the compiled tzstats files to).
For further questions, please use the tzstats repo.
```

In order to be as explicit as possible, here are the steps I followed :
0. Run a local tzindex, on port 8000. After the previous issue, it is now functional. I have been able to access it through the API, example -> `localhost:8000/explorer/status` showed that tzindex was synced
1. Cloned the TzStats repo and `cd` inside
2. `vim development.env` file, containing one line -> `TZSTATS_API_URL=http://localhost:8000`
3. `npm install`, then `yarn start`
--> At this point, the `yarn start` command launched a server on localhost:3000. It was a TzStats copy, but it was saying that it was not synced/ not connected yet, and the animated loading wheel was active.

==> Seeing that it wasn't working at this point, I continued to follow your instructions

(on a new shell, I let the Port 3000 server running on the previous one)

4. Pulled the TzStats container from docker, ran it and copied the `www/` directory inside the local `TzStats` directory. Thus, I had a `www/` directory inside my `TzStats` directory. Once done, I stopped the container
5. Cloned your `serve` repo inside the local TzStats directory too, `cd` inside and `go build main.go`
6. Added the local env variables you specified
-> `export SV_SERVER_ROOT=/home/tzstats/www`
-> `export SV_SERVER_PORT=7777`
-> `export TZSTATS_API_URL=http://localhost:8000`
7. I then `cd` inside the serve directory and ran the main executable that I just built `./main`
--> This time, it ran the same page as the `yarn start` command, but listening on port 7777.

Again, it didn't sync with my local tzindex.

Am I doing something wrong ?

I have been seeing something weird on the Tzindex logs, don't know if it is related ->
```2020/01/05 23:10:08.465764 TRCE DATA query: chain table non-indexed field 'h' for cond 0, fallback to table scan
2020/01/05 23:10:08.466025 TRCE DATA query: supply table non-indexed field 'h' for cond 0, fallback to table scan
2020/01/05 23:10:08.466295 ERRO SRVR BW-02fd8f72a866a15f02bb90971bf9151a69125b95 Error sending response: json: unsupported value: NaN in struct &server.ExplorerCycle{Cycle:0, StartHeight:1, EndHeight:64, StartTime:time.Time{wall:0x0, ext:63713288405, loc:(*time.Location)(nil)}, EndTime:time.Time{wall:0x0, ext:63713290437, loc:(*time.Location)(nil)}, Progress:100, IsComplete:true, IsSnapshot:true, IsActive:false, SnapshotHeight:0, SnapshotIndex:0, Rolls:0, RollOwners:0, StakingSupply:0, StakingPercent:NaN, ActiveBakers:3, ActiveEndorsers:0, MissedPriorities:45, MissedEndorsements:2080, N2Baking:0, N2Endorsement:0, NOrphans:1, SolveTimeMin:0, SolveTimeMax:8121393, SolveTimeMean:124975.93846153843, PriorityMin:0, PriorityMax:4, PriorityMean:0.6923076923076922, EndorsementRate:-1.5625, EndorsementsMin:0, EndorsementsMax:0, EndorsementsMean:0, SeedNonceRate:0, WorstBakedBlock:56, WorstEndorsedBlock:0, SnapshotCycle:(*server.ExplorerCycle)(0xc0000da420), FollowerCycle:(*server.ExplorerCycle)(0xc0000da840), expires:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}```

Thank you,
Guillaume

**Comment by echa** [comment]
Thanks for the detailed description. The first variant (using yarn to build the latest version and serve it on port 3000) should have worked out of the box. Can you please open your browser's development tools and check if calls are made to the API on localhost:3000 and what are the errors, if any.

The last error message is a bit strange since StakingPercent can only become NaN if the total supply on chain is zero. Assuming you run this against a sandbox network, the chain is either at height 0 (genesis) or there are no genesis accounts defined. Anyways, I pushed a small fix to the tzindex repo, but I'm not sure if that solves your problem.

**Comment by grouville** [comment]
Thank you for your awesome reactivity

Regarding the last error message, I am indeed working on a private chain. I am currently at height 714 (thus the reason I have been able to shut off all my bakers), and I activated my protocol using a personal account, so it should definitely have a genesis account defined. I'm currently in the process of testing your new fix, will let you know during the day (have to finish something before erasing my current chain) :-)

> Can you please open your browser's development tools and check if calls are made to the API on localhost:3000 and what are the errors, if any.

I had completely forgotten to check that, shame on me 😞 . I indeed have errors, and it seems that the heart of the problem is a CORS error (which surprises me, because I checked the tzindex source code and it's on `false` for localhost API calls).

Here are the errors I am getting on the console :

```
--------------
react-dom.development.js:12449 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: t
--------------
Access to fetch at 'http://localhost:8000/explorer/election/head' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
--------------
Access to fetch at 'http://localhost:8000/explorer/config/head' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
--------------
Access to fetch at 'http://localhost:8000/explorer/tip' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
--------------
Uncaught (in promise) TypeError: Failed to fetch
(I detailed it below -->)
  | async function (async) |   |  
-- | -- | -- | --
  | fetchData | @ | Election.js:14
  | (anonymous) | @ | Election.js:17
  | commitHookEffectList | @ | react-dom.development.js:22010
  | commitPassiveHookEffects | @ | react-dom.development.js:22043
  | callCallback | @ | react-dom.development.js:337
  | invokeGuardedCallbackDev | @ | react-dom.development.js:386
  | invokeGuardedCallback | @ | react-dom.development.js:439
  | flushPassiveEffectsImpl | @ | react-dom.development.js:25379
  | unstable_runWithPriority | @ | scheduler.development.js:701
  | runWithPriority$2 | @ | react-dom.development.js:12231
  | flushPassiveEffects | @ | react-dom.development.js:25348
  | performSyncWorkOnRoot | @ | react-dom.development.js:24228
  | (anonymous) | @ | react-dom.development.js:12285
  | unstable_runWithPriority | @ | scheduler.development.js:701
  | runWithPriority$2 | @ | react-dom.development.js:12231
  | flushSyncCallbackQueueImpl | @ | react-dom.development.js:12280
  | flushSyncCallbackQueue | @ | react-dom.development.js:12268
  | unbatchedUpdates | @ | react-dom.development.js:24418
  | legacyRenderSubtreeIntoContainer | @ | react-dom.development.js:27516
  | render | @ | react-dom.development.js:27596
  | render | @ | index.js:8
  | ./src/index.js | @ | index.js:11
  | __webpack_require__ | @ | bootstrap:781
  | fn | @ | bootstrap:149
  | 0 | @ | utils.js:472
  | __webpack_require__ | @ | bootstrap:781
  | checkDeferredModules | @ | bootstrap:45
  | webpackJsonpCallback | @ | bootstrap:32
  | (anonymous) | @ | main.chunk.js:1
--------------
./src/components/Accounts/TransactionHistory/PerformanceTable/PerformanceTable.js
  Line 64:6:  React Hook React.useEffect has a missing dependency: 'data.cycleId'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
--------------
Access to fetch at 'http://localhost:8000/explorer/tip' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

How can I fix it ? 😄

**Comment by echa** [comment]
That explains it. Try to set the env variable `TZ_SERVER_CORS_ENABLE=true`.

**Comment by grouville** [comment]
I exported this env variable, then I launched the server through the 2 methods, doesn't seem to fix it

**Comment by grouville** [comment]
Oh I didn't realize at first sight that this was an env variable to be put on the Tzindex shell. It is now syncing, thank you !! 😃 Will let you know when I'll get the full sync + will test right after the fix proposal you made

**Comment by grouville** [comment]
At first sight, I didn't realize it had to be for the Tzindex shell. Thank you !!! It's now fully working 😃
